/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_results__image_id__get"];
        put?: never;
        post?: never;
        /** Delete Result */
        delete: operations["delete_result_results__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result Overlay */
        get: operations["get_result_overlay_results__image_id__overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result Image */
        get: operations["get_result_image_results__image_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/enhanced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enhanced Image */
        get: operations["get_enhanced_image_results__image_id__enhanced_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/enhanced-overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enhanced Overlay */
        get: operations["get_enhanced_overlay_results__image_id__enhanced_overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance Result */
        post: operations["enhance_result_results__image_id__enhance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Delete Results */
        post: operations["batch_delete_results_results_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/batch-export/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Export Result Json */
        post: operations["batch_export_result_json_results_batch_export_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/batch-export/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Export Result Overlay */
        post: operations["batch_export_result_overlay_results_batch_export_overlay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{image_id}/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result Diagnosis
         * @description Return the saved diagnosis record only. This endpoint never triggers generation.
         */
        get: operations["get_result_diagnosis_results__image_id__diagnosis_get"];
        put?: never;
        /**
         * Generate Result Diagnosis
         * @description Generate an expert diagnosis on demand and persist it to disk.
         *     If a cached report exists and regenerate is false, return the saved content directly.
         */
        post: operations["generate_result_diagnosis_results__image_id__diagnosis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bridges */
        get: operations["list_bridges_api_v1_bridges_get"];
        put?: never;
        /** Create Bridge */
        post: operations["create_bridge_api_v1_bridges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridges/{bridge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bridge */
        get: operations["get_bridge_api_v1_bridges__bridge_id__get"];
        put?: never;
        post?: never;
        /** Delete Bridge */
        delete: operations["delete_bridge_api_v1_bridges__bridge_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_v1_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        /** Delete Batch */
        delete: operations["delete_batch_api_v1_batches__batch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batch Items */
        get: operations["list_batch_items_api_v1_batches__batch_id__items_get"];
        put?: never;
        /** Ingest Batch Items */
        post: operations["ingest_batch_items_api_v1_batches__batch_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Stats */
        get: operations["get_batch_stats_api_v1_batches__batch_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batch-items/{batch_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Item Detail */
        get: operations["get_batch_item_detail_api_v1_batch_items__batch_item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batch-items/{batch_item_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Item Result */
        get: operations["get_batch_item_result_api_v1_batch_items__batch_item_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ops Metrics */
        get: operations["get_ops_metrics_api_v1_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ops Alert Rules */
        get: operations["get_ops_alert_rules_api_v1_ops_alert_rules_get"];
        /** Update Ops Alert Rules */
        put: operations["update_ops_alert_rules_api_v1_ops_alert_rules_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/alert-rules/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops Alert Rules Audit */
        get: operations["list_ops_alert_rules_audit_api_v1_ops_alert_rules_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/process-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Next Task */
        post: operations["process_next_task_api_v1_tasks_process_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_v1_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections */
        get: operations["list_detections_api_v1_detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_api_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Alert Status */
        post: operations["update_alert_status_api_v1_alerts__alert_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCreateRequest */
        AlertCreateRequest: {
            /** Bridge Id */
            bridge_id: string;
            /** Batch Id */
            batch_id: string;
            /** Batch Item Id */
            batch_item_id?: string | null;
            /** Result Id */
            result_id?: string | null;
            /** Detection Id */
            detection_id?: string | null;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "category_hit" | "severity_exceeded" | "count_exceeded" | "trend_spike";
            /**
             * Alert Level
             * @enum {string}
             */
            alert_level: "low" | "medium" | "high" | "critical";
            /** Title */
            title: string;
            /** Trigger Payload */
            trigger_payload?: {
                [key: string]: unknown;
            };
            /** Note */
            note?: string | null;
        };
        /** AlertListResponse */
        AlertListResponse: {
            /** Items */
            items: components["schemas"]["AlertResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AlertResponse */
        AlertResponse: {
            /** Id */
            id: string;
            /** Bridge Id */
            bridge_id: string;
            /** Batch Id */
            batch_id: string;
            /** Batch Item Id */
            batch_item_id?: string | null;
            /** Result Id */
            result_id?: string | null;
            /** Detection Id */
            detection_id?: string | null;
            /** Event Type */
            event_type: string;
            /** Alert Level */
            alert_level: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Trigger Payload */
            trigger_payload?: {
                [key: string]: unknown;
            };
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AlertRulesConfigResponse */
        AlertRulesConfigResponse: {
            /**
             * Profile Name
             * @default JTG-v1
             */
            profile_name: string;
            /**
             * Alert Auto Enabled
             * @default true
             */
            alert_auto_enabled: boolean;
            /**
             * Count Threshold
             * @default 3
             */
            count_threshold: number;
            /** Category Watchlist */
            category_watchlist?: string[];
            /**
             * Category Confidence Threshold
             * @default 0.8
             */
            category_confidence_threshold: number;
            /**
             * Repeat Escalation Hits
             * @default 2
             */
            repeat_escalation_hits: number;
            /** Sla Hours By Level */
            sla_hours_by_level?: {
                [key: string]: number;
            };
            /**
             * Near Due Hours
             * @default 2
             */
            near_due_hours: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
        };
        /** AlertRulesUpdateRequest */
        AlertRulesUpdateRequest: {
            /** Updated By */
            updated_by: string;
            /** Profile Name */
            profile_name?: string | null;
            /** Alert Auto Enabled */
            alert_auto_enabled?: boolean | null;
            /** Count Threshold */
            count_threshold?: number | null;
            /** Category Watchlist */
            category_watchlist?: string[] | null;
            /** Category Confidence Threshold */
            category_confidence_threshold?: number | null;
            /** Repeat Escalation Hits */
            repeat_escalation_hits?: number | null;
            /** Sla Hours By Level */
            sla_hours_by_level?: {
                [key: string]: number;
            } | null;
            /** Near Due Hours */
            near_due_hours?: number | null;
        };
        /** AlertStatusUpdateRequest */
        AlertStatusUpdateRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "acknowledge" | "resolve";
            /** Operator */
            operator: string;
            /** Note */
            note?: string | null;
        };
        /** ArtifactLinks */
        ArtifactLinks: {
            /** Upload Path */
            upload_path: string;
            /** Json Path */
            json_path: string;
            /** Overlay Path */
            overlay_path?: string | null;
            /** Enhanced Path */
            enhanced_path?: string | null;
            /** Enhanced Overlay Path */
            enhanced_overlay_path?: string | null;
        };
        /** BatchCreateRequest */
        BatchCreateRequest: {
            /** Bridge Id */
            bridge_id: string;
            /** Batch Code */
            batch_code?: string | null;
            /** Source Type */
            source_type: string;
            /**
             * Expected Item Count
             * @default 0
             */
            expected_item_count: number;
            /** Created By */
            created_by?: string | null;
            /** Inspection Label */
            inspection_label?: string | null;
            /**
             * Enhancement Mode
             * @default always
             * @enum {string}
             */
            enhancement_mode: "off" | "auto" | "always";
        };
        /** BatchCreateResponse */
        BatchCreateResponse: {
            /** Id */
            id: string;
            /** Bridge Id */
            bridge_id: string;
            /** Bridge Code */
            bridge_code?: string | null;
            /** Bridge Name */
            bridge_name?: string | null;
            /** Batch Code */
            batch_code: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /** Sealed */
            sealed: boolean;
            /** Sealed At */
            sealed_at?: string | null;
            /** Expected Item Count */
            expected_item_count: number;
            /** Received Item Count */
            received_item_count: number;
            /** Queued Item Count */
            queued_item_count: number;
            /** Running Item Count */
            running_item_count: number;
            /** Succeeded Item Count */
            succeeded_item_count: number;
            /** Failed Item Count */
            failed_item_count: number;
            /** Created By */
            created_by?: string | null;
            /** Inspection Label */
            inspection_label?: string | null;
            /**
             * Enhancement Mode
             * @default always
             * @enum {string}
             */
            enhancement_mode: "off" | "auto" | "always";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BatchDeleteResponse */
        BatchDeleteResponse: {
            /**
             * Deleted
             * @default true
             */
            deleted: boolean;
            /** Batch Id */
            batch_id: string;
        };
        /** BatchDeleteResultItem */
        BatchDeleteResultItem: {
            /** Image Id */
            image_id: string;
            /** Deleted */
            deleted: boolean;
            /** Error Code */
            error_code?: string | null;
        };
        /** BatchDeleteResultsRequest */
        BatchDeleteResultsRequest: {
            /** Image Ids */
            image_ids?: string[];
        };
        /** BatchDeleteResultsResponse */
        BatchDeleteResultsResponse: {
            /** Requested */
            requested: number;
            /** Deleted Count */
            deleted_count: number;
            /** Failed Count */
            failed_count: number;
            /** Results */
            results?: components["schemas"]["BatchDeleteResultItem"][];
        };
        /** BatchIngestItemError */
        BatchIngestItemError: {
            /** Filename */
            filename: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** BatchIngestItemSuccess */
        BatchIngestItemSuccess: {
            /** Batch Item Id */
            batch_item_id: string;
            /** Media Asset Id */
            media_asset_id: string;
            /** Original Filename */
            original_filename: string;
            /** Source Relative Path */
            source_relative_path?: string | null;
            /** Processing Status */
            processing_status: string;
            /** Task Id */
            task_id: string;
            /**
             * Model Policy
             * @default fusion-default
             */
            model_policy: string;
            /** Requested Model Version */
            requested_model_version?: string | null;
        };
        /** BatchIngestResponse */
        BatchIngestResponse: {
            /** Batch Id */
            batch_id: string;
            /** Accepted Count */
            accepted_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Items */
            items: components["schemas"]["BatchIngestItemSuccess"][];
            /** Errors */
            errors: components["schemas"]["BatchIngestItemError"][];
        };
        /** BatchItemDetailResponse */
        BatchItemDetailResponse: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Media Asset Id */
            media_asset_id: string;
            /** Original Filename */
            original_filename?: string | null;
            /** Source Device */
            source_device?: string | null;
            /** Source Relative Path */
            source_relative_path?: string | null;
            /** Sequence No */
            sequence_no: number;
            /** Processing Status */
            processing_status: string;
            /** Review Status */
            review_status: string;
            /** Latest Task Id */
            latest_task_id?: string | null;
            /** Latest Task Status */
            latest_task_status?: string | null;
            /** Latest Task Attempt No */
            latest_task_attempt_no?: number | null;
            /** Latest Failure Code */
            latest_failure_code?: string | null;
            /** Latest Failure Message */
            latest_failure_message?: string | null;
            /** Model Policy */
            model_policy?: string | null;
            /** Requested Model Version */
            requested_model_version?: string | null;
            /** Resolved Model Version */
            resolved_model_version?: string | null;
            /** Latest Result Id */
            latest_result_id?: string | null;
            /** Defect Count */
            defect_count: number;
            /** Max Confidence */
            max_confidence?: number | null;
            /** Max Severity */
            max_severity?: string | null;
            /** Alert Status */
            alert_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            media_asset: components["schemas"]["MediaAssetResponse"];
        };
        /** BatchItemListResponse */
        BatchItemListResponse: {
            /** Items */
            items: components["schemas"]["BatchItemResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** BatchItemResponse */
        BatchItemResponse: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Media Asset Id */
            media_asset_id: string;
            /** Original Filename */
            original_filename?: string | null;
            /** Source Device */
            source_device?: string | null;
            /** Source Relative Path */
            source_relative_path?: string | null;
            /** Sequence No */
            sequence_no: number;
            /** Processing Status */
            processing_status: string;
            /** Review Status */
            review_status: string;
            /** Latest Task Id */
            latest_task_id?: string | null;
            /** Latest Task Status */
            latest_task_status?: string | null;
            /** Latest Task Attempt No */
            latest_task_attempt_no?: number | null;
            /** Latest Failure Code */
            latest_failure_code?: string | null;
            /** Latest Failure Message */
            latest_failure_message?: string | null;
            /** Model Policy */
            model_policy?: string | null;
            /** Requested Model Version */
            requested_model_version?: string | null;
            /** Resolved Model Version */
            resolved_model_version?: string | null;
            /** Latest Result Id */
            latest_result_id?: string | null;
            /** Defect Count */
            defect_count: number;
            /** Max Confidence */
            max_confidence?: number | null;
            /** Max Severity */
            max_severity?: string | null;
            /** Alert Status */
            alert_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BatchItemResultResponse */
        BatchItemResultResponse: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Batch Item Id */
            batch_item_id: string;
            /** Schema Version */
            schema_version: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Backend */
            backend: string;
            /** Inference Mode */
            inference_mode: string;
            /** Inference Ms */
            inference_ms: number;
            /** Inference Breakdown */
            inference_breakdown?: {
                [key: string]: unknown;
            };
            /** Detection Count */
            detection_count: number;
            /** Has Masks */
            has_masks: boolean;
            /** Mask Detection Count */
            mask_detection_count: number;
            /** Overlay Uri */
            overlay_uri?: string | null;
            /** Json Uri */
            json_uri?: string | null;
            /** Diagnosis Uri */
            diagnosis_uri?: string | null;
            /** Enhanced Path */
            enhanced_path?: string | null;
            /** Enhanced Overlay Path */
            enhanced_overlay_path?: string | null;
            secondary_result?: components["schemas"]["PredictResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detections */
            detections?: components["schemas"]["ResultDetectionResponse"][];
        };
        /** BatchListResponse */
        BatchListResponse: {
            /** Items */
            items: components["schemas"]["BatchResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** BatchResponse */
        BatchResponse: {
            /** Id */
            id: string;
            /** Bridge Id */
            bridge_id: string;
            /** Bridge Code */
            bridge_code?: string | null;
            /** Bridge Name */
            bridge_name?: string | null;
            /** Batch Code */
            batch_code: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /** Sealed */
            sealed: boolean;
            /** Sealed At */
            sealed_at?: string | null;
            /** Expected Item Count */
            expected_item_count: number;
            /** Received Item Count */
            received_item_count: number;
            /** Queued Item Count */
            queued_item_count: number;
            /** Running Item Count */
            running_item_count: number;
            /** Succeeded Item Count */
            succeeded_item_count: number;
            /** Failed Item Count */
            failed_item_count: number;
            /** Created By */
            created_by?: string | null;
            /** Inspection Label */
            inspection_label?: string | null;
            /**
             * Enhancement Mode
             * @default always
             * @enum {string}
             */
            enhancement_mode: "off" | "auto" | "always";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BatchStatsResponse */
        BatchStatsResponse: {
            /** Batch Id */
            batch_id: string;
            /** Status Breakdown */
            status_breakdown?: {
                [key: string]: number;
            };
            /** Review Breakdown */
            review_breakdown?: {
                [key: string]: number;
            };
            /** Category Breakdown */
            category_breakdown?: {
                [key: string]: number;
            };
            /** Alert Breakdown */
            alert_breakdown?: {
                [key: string]: number;
            };
        };
        /** Body_ingest_batch_items_api_v1_batches__batch_id__items_post */
        Body_ingest_batch_items_api_v1_batches__batch_id__items_post: {
            /** Files */
            files: string[];
            /** Relative Paths */
            relative_paths?: string[] | null;
            /** Source Device */
            source_device?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Model Policy
             * @default fusion-default
             */
            model_policy: string;
            /**
             * Enhancement Mode
             * @default always
             */
            enhancement_mode: string;
        };
        /** Body_predict_predict_post */
        Body_predict_predict_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Confidence
             * @default 0.25
             */
            confidence: number;
            /**
             * Iou
             * @default 0.45
             */
            iou: number;
            /**
             * Inference Mode
             * @default direct
             */
            inference_mode: string;
            /** Model Version */
            model_version?: string | null;
            /**
             * Return Overlay
             * @default false
             */
            return_overlay: boolean;
            /**
             * Pixels Per Mm
             * @default 10
             */
            pixels_per_mm: number;
        };
        /** BoundingBox */
        BoundingBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** BridgeCreateRequest */
        BridgeCreateRequest: {
            /** Bridge Code */
            bridge_code: string;
            /** Bridge Name */
            bridge_name: string;
            /** Bridge Type */
            bridge_type?: string | null;
            /** Region */
            region?: string | null;
            /** Manager Org */
            manager_org?: string | null;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
        };
        /** BridgeDeleteResponse */
        BridgeDeleteResponse: {
            /**
             * Deleted
             * @default true
             */
            deleted: boolean;
            /** Bridge Id */
            bridge_id: string;
        };
        /** BridgeListResponse */
        BridgeListResponse: {
            /** Items */
            items: components["schemas"]["BridgeResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** BridgeResponse */
        BridgeResponse: {
            /** Id */
            id: string;
            /** Bridge Code */
            bridge_code: string;
            /** Bridge Name */
            bridge_name: string;
            /** Bridge Type */
            bridge_type?: string | null;
            /** Region */
            region?: string | null;
            /** Manager Org */
            manager_org?: string | null;
            /** Longitude */
            longitude?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Status */
            status: string;
            /** Latest Batch Id */
            latest_batch_id?: string | null;
            /** Latest Batch Code */
            latest_batch_code?: string | null;
            /** Latest Batch Status */
            latest_batch_status?: string | null;
            /** Latest Batch Created At */
            latest_batch_created_at?: string | null;
            /**
             * Active Batch Count
             * @default 0
             */
            active_batch_count: number;
            /**
             * Abnormal Batch Count
             * @default 0
             */
            abnormal_batch_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DeleteResultResponse */
        DeleteResultResponse: {
            /**
             * Deleted
             * @default true
             */
            deleted: boolean;
            /** Image Id */
            image_id: string;
        };
        /** Detection */
        Detection: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            bbox: components["schemas"]["BoundingBox"];
            mask?: components["schemas"]["MaskPayload"] | null;
            metrics?: components["schemas"]["DetectionMetrics"];
            /** Source Role */
            source_role?: string | null;
            /** Source Model Name */
            source_model_name?: string | null;
            /** Source Model Version */
            source_model_version?: string | null;
        };
        /** DetectionListResponse */
        DetectionListResponse: {
            /** Items */
            items: components["schemas"]["DetectionRecordResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** DetectionMetrics */
        DetectionMetrics: {
            /** Length Mm */
            length_mm?: number | null;
            /** Width Mm */
            width_mm?: number | null;
            /** Area Mm2 */
            area_mm2?: number | null;
        };
        /** DetectionRecordResponse */
        DetectionRecordResponse: {
            /** Id */
            id: string;
            /** Result Id */
            result_id: string;
            /** Batch Item Id */
            batch_item_id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Severity Level */
            severity_level?: string | null;
            /** Bbox X */
            bbox_x: number;
            /** Bbox Y */
            bbox_y: number;
            /** Bbox Width */
            bbox_width: number;
            /** Bbox Height */
            bbox_height: number;
            /** Mask Payload */
            mask_payload?: {
                [key: string]: unknown;
            } | null;
            /** Length Mm */
            length_mm?: number | null;
            /** Width Mm */
            width_mm?: number | null;
            /** Area Mm2 */
            area_mm2?: number | null;
            /** Source Role */
            source_role?: string | null;
            /** Source Model Name */
            source_model_name?: string | null;
            /** Source Model Version */
            source_model_version?: string | null;
            /** Is Valid */
            is_valid: boolean;
            /** Extra Payload */
            extra_payload?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DiagnosisResponse */
        DiagnosisResponse: {
            /** Image Id */
            image_id: string;
            /** Exists */
            exists: boolean;
            /** Content */
            content?: string | null;
            /** Generated At */
            generated_at?: string | null;
        };
        /** EnhancementInfo */
        EnhancementInfo: {
            /** Algorithm */
            algorithm: string;
            /** Pipeline */
            pipeline: string;
            /** Revised Weights */
            revised_weights?: string | null;
            /** Bridge Weights */
            bridge_weights?: string | null;
            /** Generated At */
            generated_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Ready */
            ready: boolean;
            /** Active Runner */
            active_runner: string;
            /** Storage Root */
            storage_root: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** MaskPayload */
        MaskPayload: {
            /**
             * Format
             * @default polygon
             * @constant
             */
            format: "polygon";
            /** Points */
            points?: number[][];
        };
        /** MediaAssetResponse */
        MediaAssetResponse: {
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Original Filename */
            original_filename: string;
            /** Storage Uri */
            storage_uri: string;
            /** Mime Type */
            mime_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Source Device */
            source_device?: string | null;
            /** Source Relative Path */
            source_relative_path?: string | null;
        };
        /** ModelCatalogItem */
        ModelCatalogItem: {
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Backend */
            backend: string;
            /**
             * Supports Masks
             * @default true
             */
            supports_masks: boolean;
            /**
             * Supports Overlay
             * @default true
             */
            supports_overlay: boolean;
            /**
             * Supports Sliced Inference
             * @default false
             */
            supports_sliced_inference: boolean;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
        };
        /** ModelCatalogResponse */
        ModelCatalogResponse: {
            /** Active Version */
            active_version: string;
            /** Items */
            items: components["schemas"]["ModelCatalogItem"][];
        };
        /** OpsAuditLogListResponse */
        OpsAuditLogListResponse: {
            /** Items */
            items: components["schemas"]["OpsAuditLogResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** OpsAuditLogResponse */
        OpsAuditLogResponse: {
            /** Id */
            id: string;
            /** Audit Type */
            audit_type: string;
            /** Actor */
            actor: string;
            /** Target Key */
            target_key?: string | null;
            /** Before Payload */
            before_payload?: {
                [key: string]: unknown;
            };
            /** After Payload */
            after_payload?: {
                [key: string]: unknown;
            };
            /** Diff Payload */
            diff_payload?: {
                [key: string]: unknown;
            };
            /** Note */
            note?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OpsMetricsResponse */
        OpsMetricsResponse: {
            /** Window Hours */
            window_hours: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total Tasks */
            total_tasks: number;
            /** Success Rate */
            success_rate: number;
            /** Retry Recovery Rate */
            retry_recovery_rate?: number | null;
            /** Queued Tasks */
            queued_tasks: number;
            /** Running Tasks */
            running_tasks: number;
            /** Failed Tasks */
            failed_tasks: number;
            /**
             * Recovered Stale Tasks
             * @default 0
             */
            recovered_stale_tasks: number;
            /** P50 Queue Wait Ms */
            p50_queue_wait_ms?: number | null;
            /** P95 Queue Wait Ms */
            p95_queue_wait_ms?: number | null;
            /** P50 Run Ms */
            p50_run_ms?: number | null;
            /** P95 Run Ms */
            p95_run_ms?: number | null;
            /** Status Breakdown */
            status_breakdown?: {
                [key: string]: number;
            };
            /** Failure Code Breakdown */
            failure_code_breakdown?: {
                [key: string]: number;
            };
        };
        /** PredictResponse */
        PredictResponse: {
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /** Image Id */
            image_id: string;
            /**
             * Result Variant
             * @default original
             * @enum {string}
             */
            result_variant: "original" | "enhanced";
            /** Inference Ms */
            inference_ms: number;
            /** Inference Breakdown */
            inference_breakdown?: {
                [key: string]: number;
            };
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Backend */
            backend: string;
            /** Inference Mode */
            inference_mode: string;
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /**
             * Has Masks
             * @default false
             */
            has_masks: boolean;
            /**
             * Mask Detection Count
             * @default 0
             */
            mask_detection_count: number;
            enhancement_info?: components["schemas"]["EnhancementInfo"] | null;
            artifacts: components["schemas"]["ArtifactLinks"];
            secondary_result?: components["schemas"]["PredictResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ResultDetectionResponse */
        ResultDetectionResponse: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Severity Level */
            severity_level?: string | null;
            /** Bbox */
            bbox: {
                [key: string]: number;
            };
            /** Mask */
            mask?: {
                [key: string]: unknown;
            } | null;
            /** Metrics */
            metrics?: {
                [key: string]: number | null;
            };
            /** Source Role */
            source_role?: string | null;
            /** Source Model Name */
            source_model_name?: string | null;
            /** Source Model Version */
            source_model_version?: string | null;
            /**
             * Is Valid
             * @default true
             */
            is_valid: boolean;
        };
        /** ResultEnhanceRequest */
        ResultEnhanceRequest: {
            /** Requested By */
            requested_by: string;
            /** Reason */
            reason?: string | null;
        };
        /** ResultListResponse */
        ResultListResponse: {
            /** Items */
            items: components["schemas"]["ResultSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
        };
        /** ResultSummary */
        ResultSummary: {
            /** Image Id */
            image_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Backend */
            backend: string;
            /** Inference Mode */
            inference_mode: string;
            /** Inference Ms */
            inference_ms: number;
            /** Inference Breakdown */
            inference_breakdown?: {
                [key: string]: number;
            };
            /** Detection Count */
            detection_count: number;
            /**
             * Has Masks
             * @default false
             */
            has_masks: boolean;
            /**
             * Mask Detection Count
             * @default 0
             */
            mask_detection_count: number;
            /**
             * Has Diagnosis
             * @default false
             */
            has_diagnosis: boolean;
            /** Categories */
            categories?: string[];
            artifacts: components["schemas"]["ArtifactLinks"];
        };
        /** ReviewCreateRequest */
        ReviewCreateRequest: {
            /** Detection Id */
            detection_id: string;
            /**
             * Review Action
             * @enum {string}
             */
            review_action: "confirm" | "reject" | "edit";
            /** Reviewer */
            reviewer: string;
            /** Review Note */
            review_note?: string | null;
            /** After Payload */
            after_payload?: {
                [key: string]: unknown;
            };
        };
        /** ReviewListResponse */
        ReviewListResponse: {
            /** Items */
            items: components["schemas"]["ReviewRecordResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReviewRecordResponse */
        ReviewRecordResponse: {
            /** Id */
            id: string;
            /** Batch Item Id */
            batch_item_id: string;
            /** Result Id */
            result_id: string;
            /** Detection Id */
            detection_id: string;
            /** Review Action */
            review_action: string;
            /** Review Decision */
            review_decision: string;
            /** Before Payload */
            before_payload?: {
                [key: string]: unknown;
            };
            /** After Payload */
            after_payload?: {
                [key: string]: unknown;
            };
            /** Review Note */
            review_note?: string | null;
            /** Reviewer */
            reviewer: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TaskProcessResponse */
        TaskProcessResponse: {
            /** Processed */
            processed: boolean;
            /** Message */
            message?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Result Id */
            result_id?: string | null;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Id */
            id: string;
            /** Batch Item Id */
            batch_item_id: string;
            /** Task Type */
            task_type: string;
            /** Status */
            status: string;
            /** Attempt No */
            attempt_no: number;
            /** Priority */
            priority: number;
            /** Model Policy */
            model_policy: string;
            /** Requested Model Version */
            requested_model_version?: string | null;
            /** Resolved Model Version */
            resolved_model_version?: string | null;
            /** Inference Mode */
            inference_mode: string;
            /** Queued At */
            queued_at?: string | null;
            /** Claimed At */
            claimed_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Worker Name */
            worker_name?: string | null;
            /** Runtime Payload */
            runtime_payload?: {
                [key: string]: unknown;
            };
            /** Timing Payload */
            timing_payload?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskRetryRequest */
        TaskRetryRequest: {
            /** Requested By */
            requested_by: string;
            /** Reason */
            reason?: string | null;
        };
        /** TaskRetryResponse */
        TaskRetryResponse: {
            /** Old Task Id */
            old_task_id: string;
            /** New Task Id */
            new_task_id: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogResponse"];
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_predict_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_results_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_results__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_result_results__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_overlay_results__image_id__overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_image_results__image_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enhanced_image_results__image_id__enhanced_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enhanced_overlay_results__image_id__enhanced_overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enhance_result_results__image_id__enhance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEnhanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_results_results_batch_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_export_result_json_results_batch_export_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_export_result_overlay_results_batch_export_overlay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_diagnosis_results__image_id__diagnosis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_result_diagnosis_results__image_id__diagnosis_post: {
        parameters: {
            query?: {
                regenerate?: boolean;
            };
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bridges_api_v1_bridges_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bridge_api_v1_bridges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BridgeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bridge_api_v1_bridges__bridge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bridge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bridge_api_v1_bridges__bridge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bridge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_batches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                bridge_id?: string | null;
                status_filter?: string | null;
                has_failures?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_v1_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_batch_api_v1_batches__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batch_items_api_v1_batches__batch_id__items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                relative_path_prefix?: string | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_batch_items_api_v1_batches__batch_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_batch_items_api_v1_batches__batch_id__items_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_stats_api_v1_batches__batch_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_item_detail_api_v1_batch_items__batch_item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchItemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_item_result_api_v1_batch_items__batch_item_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchItemResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_metrics_api_v1_ops_metrics_get: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_alert_rules_api_v1_ops_alert_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRulesConfigResponse"];
                };
            };
        };
    };
    update_ops_alert_rules_api_v1_ops_alert_rules_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRulesUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRulesConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_alert_rules_audit_api_v1_ops_alert_rules_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                actor?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsAuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_next_task_api_v1_tasks_process_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskProcessResponse"];
                };
            };
        };
    };
    retry_task_api_v1_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_api_v1_detections_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                batch_item_id?: string | null;
                category?: string | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                min_area_mm2?: number | null;
                is_valid?: boolean | null;
                sort_by?: "created_at" | "confidence" | "area_mm2";
                sort_order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                batch_item_id?: string | null;
                detection_id?: string | null;
                reviewer?: string | null;
                sort_by?: "reviewed_at" | "created_at";
                sort_order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                status_filter?: string | null;
                event_type?: string | null;
                sort_by?: "triggered_at" | "created_at" | "updated_at";
                sort_order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_status_api_v1_alerts__alert_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
