from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Optional, Protocol, Union, runtime_checkable

from sqlalchemy.orm import Session, sessionmaker

if TYPE_CHECKING:
    from fastapi import UploadFile

    from app.adapters.enhancement_runner import DualBranchEnhanceRunner
    from app.adapters.manager import RunnerManager
    from app.db.models import BatchItem, Bridge, InspectionBatch, InferenceTask
    from app.models.schemas import (
        AlertCreateRequest,
        AlertResponse,
        BatchCreateRequest,
        BatchIngestItemError,
        BridgeResponse,
        FailureDecision,
        RawPrediction,
        ReviewCreateRequest,
        ReviewRecordResponse,
    )
    from app.storage.local import LocalArtifactStore


@runtime_checkable
class BatchServiceLike(Protocol):
    session_factory: sessionmaker[Session]
    store: LocalArtifactStore
    runner_manager: Optional[RunnerManager]
    max_upload_size_bytes: int
    alert_sla_hours_by_level: dict[str, int]

    def _new_id(self, prefix: str) -> str: ...
    def _normalize_relative_path(self, value: Optional[str]) -> Optional[str]: ...
    def _validate_relative_paths(self, *, files: list[UploadFile], relative_paths: Optional[list[str]]) -> None: ...
    def _validate_model_policy(self, model_policy: str) -> str: ...
    def _validate_enhancement_mode(self, enhancement_mode: str) -> str: ...
    def _resolve_requested_model_version(self, model_policy: str) -> Optional[str]: ...
    def _should_enable_enhancement(self, *, content: bytes, enhancement_mode: str) -> bool: ...
    def _refresh_batch_aggregates(self, *, session: Session, batch_id: str) -> None: ...
    def _refresh_batch_item_alert_status(self, *, session: Session, batch_item_id: str) -> None: ...
    def _reconcile_batch_aggregates(self, *, session: Session, batch: InspectionBatch) -> bool: ...
    def _generate_batch_code(self, *, session: Session, bridge: Bridge, attempt_offset: int = 0) -> str: ...
    def _build_bridge_response(self, *, session: Session, bridge: Bridge) -> BridgeResponse: ...
    def _build_batch_payload(self, *, session: Session, batch: InspectionBatch, bridge: Optional[Bridge], payload: Optional[BatchCreateRequest] = None) -> dict[str, object]: ...
    def _build_alert_trigger_payload(self, base_payload: dict[str, object], alert_level: str) -> dict[str, object]: ...
    def _build_sla_due_at_iso(self, level: str, start_at: datetime) -> str: ...
    def _apply_overdue_alert_escalation(self, *, session: Session) -> None: ...
    def _percentile_int(self, values: list[int], p: float) -> Optional[int]: ...
    async def _validate_upload(self, file: UploadFile) -> tuple[bool, Optional[BatchIngestItemError]]: ...
    async def _read_upload_content(self, file: UploadFile) -> bytes: ...


@runtime_checkable
class TaskServiceLike(Protocol):
    session_factory: sessionmaker[Session]
    store: LocalArtifactStore
    runner_manager: RunnerManager
    enhance_runner: Optional[DualBranchEnhanceRunner]
    max_attempts: int
    task_lease_seconds: int
    alert_auto_enabled: bool
    alert_count_threshold: int
    alert_category_watchlist: list[str]
    alert_category_confidence_threshold: float
    alert_repeat_escalation_hits: int
    alert_near_due_hours: int
    alert_sla_hours_by_level: dict[str, int]
    alert_profile_name: str
    alert_updated_at: datetime
    alert_updated_by: Optional[str]
    ALERT_RULES_CONFIG_KEY: str
    failure_decision_class: type[FailureDecision]
    auto_alert_candidate_class: type
    normalize_category: object

    def _new_id(self, prefix: str) -> str: ...
    def _resolve_storage_path(self, storage_uri: str) -> Path: ...
    def _touch_task_lease(self, task: InferenceTask) -> None: ...
    def _resolve_requested_model_version(self, model_policy: str) -> Optional[str]: ...
    def _claim_next_queued_task(self, *, session: Session, worker_name: str) -> Optional[InferenceTask]: ...
    def _execute_task(self, session: Session, task: InferenceTask) -> str: ...
    def _classify_failure(self, exc: Exception) -> FailureDecision: ...
    def _refresh_batch_aggregates(self, *, session: Session, batch_id: str) -> None: ...
    def _emit_auto_alerts(self, *, session: Session, batch_item: BatchItem, result_id: str, raw: RawPrediction) -> None: ...
    def _build_auto_alert_candidates(self, raw: RawPrediction) -> list: ...
    def _build_alert_trigger_payload(self, base_payload: dict[str, object], alert_level: str) -> dict[str, object]: ...
    def _build_sla_due_at_iso(self, level: str, start_at: datetime) -> str: ...
    def _next_alert_level(self, level: str) -> str: ...
    def _build_alert_rules_payload(self) -> dict[str, object]: ...
    def _sync_alert_rules_from_db(self, *, session: Session) -> None: ...
    def _build_result_json(self, *, result_id: str, batch_item_id: str, raw: RawPrediction, upload_uri: Optional[str] = None, overlay_uri: Optional[str] = None, secondary_raw: Optional[RawPrediction] = None, enhanced_uri: Optional[str] = None, enhanced_overlay_uri: Optional[str] = None, enhancement_meta: Optional[dict[str, str]] = None, created_at: Optional[datetime] = None) -> dict[str, object]: ...
    def _mark_task_failed(self, task_id: str, *, decision: FailureDecision, allow_auto_retry: bool) -> Optional[str]: ...
    def _is_retryable_failure_code(self, code: Optional[str]) -> bool: ...
    def _next_attempt_no(self, *, session: Session, batch_item_id: str) -> int: ...
    def _create_retry_task(self, *, session: Session, source_task: InferenceTask, attempt_no: int, requested_by: str, reason: Optional[str]) -> InferenceTask: ...